
const jobCards = {
  segmentation: {
    file: 'nuclei/examples/HeLa_nuclear.png',
    name: 'Nuclear Segmentation',
    model: 'The nuclear model performs nuclear segmentation of cell culture data.',
    inputs: 'A nuclear channel image.',
    resolution: 'Nuclear Segmentation expects data that is approximately 20X (0.65 μm/pixel)',
    thumbnail: 'thumbnails/HeLa_nuclear_color.png',
    scaleEnabled: true,
    channelEnabled: true,
    requiredChannels: ['nuclei'],
    modelResolution: 0.5,
    canOpenInLabel: true,
  },
  caliban: {
    file: 'tiff_stack_examples/3T3_nuc_example_256.tif',
    name: 'Cell Tracking',
    model: 'The cell tracking model segments and tracks objects over time and creates a lineage file for division information.',
    inputs: 'A single-channel image stack (3D TIFF).',
    resolution: 'Cell Tracking expects data that is approximately 20X (0.65 μm/pixel)',
    thumbnail: 'thumbnails/3T3_nuc_example_256.png',
    scaleEnabled: true,
    channelEnabled: true,
    requiredChannels: ['nuclei'],
    modelResolution: 0.5,
    canOpenInLabel: true,
  },
  mesmer: {
    file: 'tiff_stack_examples/vectra_breast_cancer.tif',
    name: 'Mesmer',
    model: 'Mesmer performs whole-cell segmentation of multiplex tissue data.',
    inputs: 'An image containing both a nuclear marker and a membrane/cytoplasm marker.',
    resolution: 'Mesmer expects data that is approximately 20X (0.5 μm/pixel)',
    thumbnail: 'thumbnails/breast_vectra.png',
    scaleEnabled: true,
    channelEnabled: true,
    requiredChannels: ['nuclei', 'cytoplasm'],
    modelResolution: 0.5,
    canOpenInLabel: true,
  },
  polaris: {
    file: 'tiff_stack_examples/MERFISH_example.tiff',
    name: 'Polaris',
    model: 'Polaris performs fluorescent spot detection.',
    inputs: 'An image containing fluorescent spots generated by smFISH or similar assays. Pixel size of 0.1 μm recommended.',
    resolution: 'Polaris expects data that is approximately 100X (0.1 μm/pixel)',
    thumbnail: 'thumbnails/FISH_example.png',
    scaleEnabled: false,
    channelEnabled: false,
    requiredChannels: ['spots'],
    modelResolution: 0.1,
    canOpenInLabel: false,
  },
};

// TODO: this is a stop gap to support both multiplex and mesmer names
jobCards.multilplex = jobCards.mesmer;
// TODO: this is a stop gap to support both tracking and caliban names
jobCards.tracking = jobCards.caliban;

export default jobCards;
