sudo: false
dist: trusty

language: node_js

node_js:
  - 8
  - 10
  - node

cache:
  yarn: true
  directories:
    - .npm
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install: true

script:
  - yarn test

jobs:
  include:
    - stage: deploy
      if: (branch = master OR branch =~ ^r[0-9]+.[0-9]+) AND type != pull_request
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t "$TRAVIS_REPO_SLUG" .
      - docker images
      - docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":latest
      - if [[ "$TRAVIS_BRANCH" != "master" ]] ; then docker tag "$TRAVIS_REPO_SLUG" "$TRAVIS_REPO_SLUG":"${TRAVIS_BRANCH#r}" ; fi
      - docker push "$TRAVIS_REPO_SLUG"
