########################################
#DEPLOYMENT VERSION
########################################
#This docker section will serve the express server and the dist file that contains the react webpack.

FROM node:carbon

RUN apt-get update

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install
COPY server.js ./
COPY ./server ./server

#ENV PORT=8080

#EXPOSE $PORT

# Run the server
ENTRYPOINT [ "npm", "start" ]